### ISSUE TITLE
Creating snapcraft.yaml file for snap app

### ISSUE THREAD

**Issue by letozaf** [oguzhaninan/Stacer#119]
Hi,
I wanted to create a snapcraft.yaml file for creating a snap of Stacer (https://snapcraft.io/).
For doing so I first wanted to build from source to see how to install it so to be able to create the snapcraft.yaml file.
I am trying to build Stacer on Ubuntu 17.04 but, even if qmake is installed I get the error here under, in Ubuntu qmake is in /usr/bin/qmake.
Can you help me solve this issue so to build Stacer form source and make a PR for the snapcraft.yaml file?

carla@carla-VirtualBox:~/Stacer$ ./deploy.sh 
./deploy.sh: line 19: /bin/qmake: No such file or directory
./deploy.sh: line 21: cd: /home/carla/Stacer/dist/build/stacer-core: No such file or directory
./deploy.sh: line 22: cd: /home/carla/Stacer/dist/build/stacer: No such file or directory
mkdir: cannot create directory ‘/home/carla/Stacer/dist/build/stacer/lib’: No such file or directory
cp: cannot stat '/home/carla/Stacer/dist/build/stacer-core/libstacer-core.so.1.0.0': No such file or directory
Info: creating stash file /home/carla/Stacer/.qmake.stash
WARNING: Project ERROR: Unknown module(s) in QT: charts svg
Updating '/home/carla/Stacer/stacer/../translations/stacer_en.qm'...
    Generated 0 translation(s) (0 finished and 0 unfinished)
    Ignored 83 untranslated source text(s)
Updating '/home/carla/Stacer/stacer/../translations/stacer_es.qm'...
    Generated 82 translation(s) (82 finished and 0 unfinished)
    Ignored 1 untranslated source text(s)
Updating '/home/carla/Stacer/stacer/../translations/stacer_fr.qm'...
    Generated 83 translation(s) (83 finished and 0 unfinished)
Updating '/home/carla/Stacer/stacer/../translations/stacer_pt.qm'...
    Generated 83 translation(s) (83 finished and 0 unfinished)
Updating '/home/carla/Stacer/stacer/../translations/stacer_sv.qm'...
    Generated 83 translation(s) (83 finished and 0 unfinished)
Updating '/home/carla/Stacer/stacer/../translations/stacer_tr.qm'...
    Generated 83 translation(s) (83 finished and 0 unfinished)
Updating '/home/carla/Stacer/stacer/../translations/stacer_hi.qm'...
    Generated 83 translation(s) (83 finished and 0 unfinished)
mkdir: cannot create directory ‘/home/carla/Stacer/dist/build/stacer/translations’: No such file or directory
mv: target '/home/carla/Stacer/dist/build/stacer/translations' is not a directory
find: ‘/home/carla/Stacer/dist/build/stacer’: No such file or directory
./deploy.sh: line 39: cd: /home/carla/Stacer/dist/build/stacer: No such file or directory
./deploy.sh: line 48: linuxdeployqt: command not found
rm: cannot remove '/home/carla/Stacer/dist/build/stacer/AppRun': No such file or directory
rm: cannot remove '/home/carla/Stacer/dist/build/stacer/.DirIcon': No such file or directory

Thanks Carla

**Comment by lilianmoraru** [comment]
The script seems to be specific to the author's environment(uses `QTDIR` environment variable which people usually do not define).

Also, usually the qmake you have in the system(Qt actually) is not enough for a software build(doesn't have all the dependencies usually).
Consider installing Qt from here: https://download.qt.io/official_releases/qt/5.9/5.9.1/qt-opensource-linux-x64-5.9.1.run
After you downloaded it(usually it goes in `~/Downloads` so I will give examples with that path), you need to:
- make the installer executable(terminal command): `chmod u+x ~/Downloads/qt-opensource-linux-x64-5.9.1.run`
- execute the installer: `~/Downloads/qt-opensource-linux-x64-5.9.1.run --no-force-installations`(the default is to install in `~/Qt5.9.1` in this case, so lets leave it like this. You need to basically press "Next" until it finishes although I would remove the Android binaries because you don't need them)

After you installed Qt, you need to export the `QTDIR` environment variable that the script requires:
```
export QTDIR="$(readlink -m "${HOME:?}/Qt5.9.1/5.9.1/gcc_64")"
```

Now you should be able to run the script.

**Comment by lilianmoraru** [comment]
Also, the author uses https://github.com/probonopd/linuxdeployqt which you most probably don't have in the system.

**Comment by letozaf** [comment]
Thanks for the info.
I will try as you say and let you know.

Carla
