### ISSUE TITLE
Dashboard's 'System Info' does not report CPU Speed for Ryzen 7 1700

### ISSUE THREAD

**Issue by TheFlagCourier** [oguzhaninan/Stacer#218]
## Issue
Stacer does not detect the "CPU Speed" for AMD Ryzen 7 1700 on the Dashboard, and may effect other processors. CPU utilization percentages do not appear to be affected.

## Test Environment
- Stacer Version 1.0.9 (from RPM)
- Fedora Workstation 28
- Kernel 4.16.14 with Fedora kernel patches.
- CPU: AMD's Ryzen 7 1700, 8-Core, 16 Threads.

## Example:
![image](https://user-images.githubusercontent.com/2712890/41392322-9bde05d0-6f65-11e8-951e-c378fe0ceeff.png)

## Closing Notes
- This may be the result of manually overclocking through the UEFI shell? `sudo dmidecode -t processor | grep "Speed"` appears to get the proper output.
    ```
     Max Speed: 3750 MHz
     Current Speed: 3100 MHz
    ```
- Can provide more information on request, not sure what I might be missing if applicable.

**Comment by TheFlagCourier** [comment]
Sorry, fat-fingered return...

**Comment by oguzhaninan** [comment]
Thank you for warning. I will fix it in the new version.

**Comment by TheeMahn** [comment]
I built Operating Systems for fun & intend to integrate and replace when I can the system monitoring tool for almost all DE's with yours.  I have built a Operating system builder.  Can build 5,500+ operating systems.  I find 2 flaws in your application.  A memory mis-reporting or leak.  I bet the first to be the factor. #2 has been pointed out does not Ryzen 7 1700X as in my case.
![screenshot_20180708_101840](https://user-images.githubusercontent.com/18008394/42420750-561c7acc-8298-11e8-9f6c-6db9df516757.png)

You have built an awesome application.  I am going to get you the exposure you deserve.  We have millions of downloads at avg gigabytes per download.  If your application is built in, what kind of exposure will you see?

I probably should save you some time and start breaking things down for you, we own 13 domains & host off 32 servers, 2 out of my basement.
http://os-builder.com
https://ultimateedition.info/
https://sourceforge.net/projects/ultimateedition/files/

Basement 1 of 2:
http://keyserver.ueserver.space:19999 (untested AMD 32 core server 32GB of ram, 32GB more coming, 20TB+ of space)

I hope that motivates you.

**Comment by gardotd426** [comment]
This issue is not fixed, at least not on Zen+/second-gen Ryzen. I had a third-gen ryzen chip before (3200G) and I'm pretty sure it didn't work with it, either. But I know it doesn't work with 2nd Gen 2600X. `/proc/cpuinfo` as well as `sudo dmidecode -t processor | grep -i "speed" report the correct speed, as do `nmon` and `sudo cpupower frequency-info`, along with geekbench and phoronix. Oh and `neofetch` reports it correctly too. 
![Screenshot_20200120_080508](https://user-images.githubusercontent.com/54234607/72728643-daf87480-3b5b-11ea-958d-616acb71ec35.png)

```
sudo dmidecode -t processor | grep -i "speed"
	Max Speed: 4250 MHz
	Current Speed: 4075 MHz
```

![Screenshot_20200120_081007](https://user-images.githubusercontent.com/54234607/72728851-4d695480-3b5c-11ea-9f2c-d7d47289fc94.png)

**Comment by gardotd426** [comment]
I also just noticed that there's some ridiculous memory issue as well, those screenshots were taken at the same time, yet stacer reports me using 13GB of RAM which is crazy. 

EDIT: The second problem (the RAM reporting) seems to be some type of memory leak. If I run the following: 
```
sync; echo 1 > /proc/sys/vm/drop_caches
sync; echo 2 > /proc/sys/vm/drop_caches
sync; echo 3 > /proc/sys/vm/drop_caches
```
...as superuser, the RAM usage-ometer (lol) immediately scales wayyyy down and back to normal. Immediately after the first screenshot, after typing those commands, this is now what stacer looks like 
![Screenshot_20200120_082420](https://user-images.githubusercontent.com/54234607/72729902-44798280-3b5e-11ea-9264-8a18ba89d974.png)

Should I open a new issue for that? Both issues are incorrect reporting, but since one is for RAM and one CPU idk if you want me to open a separate issue. I love this app, I use it on every install I do, but the RAM misreporting thing is wild, and the cpu misreporting thing is very unfortunate. I'm not sure though if I've ever noticed the RAM reporting craziness on my Manjaro install, I'll check it next time I boot into it.

**Comment by LucasMaxShell** [comment]
I also seem to be having this issue but on a Ryzen 7 2700X:
terminal reports the speed just fine:
	Max Speed: 4350 MHz
	Current Speed: 3700 MHz

![Image](https://github.com/user-attachments/assets/24551185-ce5d-409a-9a68-09ac9f411175)

Hope this helps, besides this issue really enjoying this tool!

**Comment by TheFlagCourier** [comment]
@LucasMaxShell 
Hey, I was going to say that you should make your own issue report and reference this one - but it seems Stacer has been abandoned for the last two years. It would be better to [check for any forks](https://github.com/oguzhaninan/Stacer/network), or look for an alternative at this point.

@oguzhaninan 
If you're still around, you may want to archive this repository in the repo settings.
