### ISSUE TITLE
Stacer doesn't work with my lubuntu 18.04.1

### ISSUE THREAD

**Issue by kundelmitch** [oguzhaninan/Stacer#247]
Hello,
I installed as described here for ubuntu : https://github.com/oguzhaninan/Stacer
Nothing happens when I click on icon in main menu (only clock on the mouse pointer a few seconds) / accessories and there is no icon on my desktop. 
Did I make something wrong ?

**Comment by m-flak** [comment]
Run it from the terminal and copy-paste its output.

**Comment by kundelmitch** [comment]
bash: /usr/bin/stacer : impossible d'exécuter le fichier binaire : Erreur de format pour exec()

**Comment by kundelmitch** [comment]
I have the same problem with lubuntu 16.04 ...

**Comment by m-flak** [comment]
Compile it from source.

**Comment by m-flak** [comment]
Oh, and, I believe that you have installed the wrong architecture *.deb so if you did [follow this guide](https://wiki.debian.org/Multiarch/HOWTO) and report back in.

**Comment by kundelmitch** [comment]
Unfortunately, I'm beginner with lubuntu and don't understand how to proceed with your 2 last tips ...
Can you give me more details please ?
Thank you in advance !

**Comment by m-flak** [comment]
I included a link from the Debian wiki. You literally just follow the
instructions and copy-paste the commands to enable multiarch. Try that and
report back. Here's the link:
https://wiki.debian.org/Multiarch

On Dec 5, 2018 3:15 AM, "kundelmitch" <notifications@github.com> wrote:

Unfortunately, I'm beginner with lubuntu and don't understand how to
proceed with your 2 last tips ...
Can you give me more details please ?
Thank you in advance !

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/oguzhaninan/Stacer/issues/247#issuecomment-444414077>,
or mute the thread

**Comment by breznak** [comment]
running fine here on 18.04.1, installed from PPA as the Readme says.
