### ISSUE TITLE
is this maintaind ?

### ISSUE THREAD

**Issue by Cuteistfox** [oguzhaninan/Stacer#526]
the last commits from 2022

**Comment by jason-eu** [comment]
No, the project is abandoned for some time

**Comment by KryptonNerd** [comment]
> No, the project is abandoned for some time

This is a real shame, this project had so much promise

**Comment by simone80an** [comment]
@KryptonNerd i quote you and i still use it and find very useful.
Hope someone can keep up this project!
For system cleaner maybe can be written a small shell script that does the same job with some implementations (eg. cleaning unused Flatpak). Someone knows the exact commands and folder that it looks for cleaning package caches, crash reports, application logs, application caches and trash?

**Comment by oguzhaninan** [comment]
This project has been abandoned. There will be no further releases.

Open-source project development has serious difficulties. Many articles have been written on this issue, so I can't continue anymore because I have similar problems, and I don't even have time to write this comment. 🙂

Anyone who wishes can continue by forking the project. ✋

There is a good article about open source

https://archive.jlongster.com/Why-Frequently-Absent-Open-Source
